# Enterprise Procurement & Vendor Performance Analytics
# Day 11 - Data Cleaning Reproduction

# Objective:
# Reproduce the data cleaning process performed on Day 8
# and validate that the cleaned datasets match the cleaning plan.

**purchase_prices**

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\purchase_prices.csv")

print(df.shape)
df.head()

(12261, 9)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           12261 non-null  int64
 1   Description     12260 non-null  object
 2   Price           12261 non-null  float64
 3   Size            12260 non-null  object
 4   Volume          12260 non-null  object
 5   Classification  12261 non-null  int64
 6   PurchasePrice   12261 non-null  float64
 7   VendorNumber    12261 non-null  int64
 8   VendorName      12261 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 862.2+ KB

In [4]:
df.isnull().sum()

Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
# Remove rows where Description, Size or Volume are missing
df = df.dropna(subset=["Description", "Size", "Volume"])

# Convert Volume to numeric
# Any non-numeric value (like "Unknown") becomes NaN
df["Volume"] = pd.to_numeric(df["Volume"], errors="coerce")

# Remove rows where Volume became NaN
df = df.dropna(subset=["Volume"])

# Convert Volume to integer
df["Volume"] = df["Volume"].astype(int)

print(df.shape)

(12256, 9)

In [7]:
df.isnull().sum()

Brand             0
Description       0
Price             0
Size              0
Volume            0
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [87]:
df = pd.read_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\python data cleaning\purchase_prices_cleaned.csv"
)

print(df.shape)

# Check for new lines in Description
print(df[df["Description"].astype(str).str.contains("\n|\r", regex=True, na=False)])

# Check datatypes
print(df.dtypes)

# Save again
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\python data cleaning\purchase_prices_cleaned_new.csv",
    index=False,
    encoding="utf-8",
    lineterminator="\n"
)

(12256, 9)
Empty DataFrame
Columns: [Brand, Description, Price, Size, Volume, Classification, PurchasePrice, VendorNumber, VendorName]
Index: []
Brand               int64
Description        object
Price             float64
Size               object
Volume              int64
Classification      int64
PurchasePrice     float64
VendorNumber        int64
VendorName         object
dtype: object

In [88]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\purchase_prices_cleaned.csv",
    index=False
)

print("purchase_prices_cleaned.csv saved successfully")

purchase_prices_cleaned.csv saved successfully

**vendor_invoice**

In [9]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\vendor_invoice.csv")

print(df.shape)

df.head()

(5543, 10)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,1/4/2024,8124,12/21/2023,2/16/2024,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,1/7/2024,8137,12/22/2023,2/21/2024,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,1/9/2024,8169,12/24/2023,2/16/2024,5,106.60,4.61,NaN
3,480,BACARDI USA INC,1/12/2024,8106,12/20/2023,2/5/2024,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,1/7/2024,8170,12/24/2023,2/12/2024,1935,15527.25,429.20,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   object
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   object
 5   PayDate       5543 non-null   object
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
 9   Approval      374 non-null    object
dtypes: float64(2), int64(3), object(5)
memory usage: 433.2+ KB

In [11]:
df.isnull().sum()

VendorNumber       0
VendorName         0
InvoiceDate        0
PONumber           0
PODate             0
PayDate            0
Quantity           0
Dollars            0
Freight            0
Approval        5169
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
# Remove Approval column
df = df.drop(columns=["Approval"])

# Convert date columns to datetime
date_columns = ["InvoiceDate", "PODate", "PayDate"]

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   datetime64[ns]
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   datetime64[ns]
 5   PayDate       5543 non-null   datetime64[ns]
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
dtypes: datetime64[ns](3), float64(2), int64(3), object(1)
memory usage: 389.9+ KB
None

In [14]:
df.isnull().sum()

VendorNumber    0
VendorName      0
InvoiceDate     0
PONumber        0
PODate          0
PayDate         0
Quantity        0
Dollars         0
Freight         0
dtype: int64

In [16]:
pd.to_datetime(df[col])

0      2024-02-16
1      2024-02-21
2      2024-02-16
3      2024-02-05
4      2024-02-12
          ...
5538   2025-02-10
5539   2025-02-18
5540   2025-02-04
5541   2025-02-08
5542   2025-02-12
Name: PayDate, Length: 5543, dtype: datetime64[ns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   datetime64[ns]
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   datetime64[ns]
 5   PayDate       5543 non-null   datetime64[ns]
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
dtypes: datetime64[ns](3), float64(2), int64(3), object(1)
memory usage: 389.9+ KB

In [18]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\vendor_invoice_cleaned.csv",
    index=False
)

print("vendor_invoice_cleaned.csv saved successfully")

vendor_invoice_cleaned.csv saved successfully

**vendor_sales_summary**

In [20]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\vendor_sales_summary.csv")

print(df.shape)

df.head()

(10692, 18)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26,37,1750,145080,3811252,142049,672819,5101920,260999,68602,1290668,25,1,1
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23,29,1750,164038,3804041,160247,561512,4819073,294439,144929,1015032,21,1,1
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18,25,1750,187407,3418304,187140,461140,4538121,343854,123780,1119817,25,1,1
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16,23,1750,201682,3261198,200412,420050,4475973,368243,257032,1214775,27,1,1
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,22,30,1750,138109,3023206,135838,545778,4223108,249588,257032,1199902,28,1,1

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10692 entries, 0 to 10691
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10692 non-null  int64
 1   VendorName             10692 non-null  object
 2   Brand                  10692 non-null  int64
 3   Description            10692 non-null  object
 4   PurchasePrice          10692 non-null  int64
 5   ActualPrice            10692 non-null  int64
 6   Volume                 10692 non-null  int64
 7   TotalPurchaseQuantity  10692 non-null  int64
 8   TotalPurchaseDollars   10692 non-null  int64
 9   TotalSalesQuantity     10692 non-null  int64
 10  TotalSalesPrice        10692 non-null  int64
 11  TotalSalesDollars      10692 non-null  int64
 12  TotalExciseTax         10692 non-null  int64
 13  FreightCost            10692 non-null  int64
 14  GrossProfit            10692 non-null  int64
 15  ProfitMargin           10692 non-null  object
 16  StockTurnover          10692 non-null  int64
 17  SalestoPurchaseRatio   10692 non-null  int64
dtypes: int64(15), object(3)
memory usage: 1.5+ MB

In [22]:
df.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesPrice          0
TotalSalesDollars        0
TotalExciseTax           0
FreightCost              0
GrossProfit              0
ProfitMargin             0
StockTurnover            0
SalestoPurchaseRatio     0
dtype: int64

In [23]:
df.duplicated().sum()

0

In [24]:
# Convert ProfitMargin to numeric
df["ProfitMargin"] = pd.to_numeric(df["ProfitMargin"], errors="coerce")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10692 entries, 0 to 10691
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10692 non-null  int64
 1   VendorName             10692 non-null  object
 2   Brand                  10692 non-null  int64
 3   Description            10692 non-null  object
 4   PurchasePrice          10692 non-null  int64
 5   ActualPrice            10692 non-null  int64
 6   Volume                 10692 non-null  int64
 7   TotalPurchaseQuantity  10692 non-null  int64
 8   TotalPurchaseDollars   10692 non-null  int64
 9   TotalSalesQuantity     10692 non-null  int64
 10  TotalSalesPrice        10692 non-null  int64
 11  TotalSalesDollars      10692 non-null  int64
 12  TotalExciseTax         10692 non-null  int64
 13  FreightCost            10692 non-null  int64
 14  GrossProfit            10692 non-null  int64
 15  ProfitMargin           10514 non-null  float64
 16  StockTurnover          10692 non-null  int64
 17  SalestoPurchaseRatio   10692 non-null  int64
dtypes: float64(1), int64(15), object(2)
memory usage: 1.5+ MB
None

In [25]:
df.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity         0
TotalSalesPrice            0
TotalSalesDollars          0
TotalExciseTax             0
FreightCost                0
GrossProfit                0
ProfitMargin             178
StockTurnover              0
SalestoPurchaseRatio       0
dtype: int64

In [27]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\vendor_sales_summary_cleaned.csv",
    index=False
)

print("vendor_sales_summary_cleaned.csv saved successfully")

vendor_sales_summary_cleaned.csv saved successfully

**purchases_sample**

In [29]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\purchases_sample.csv")

print(df.shape)
df.head()

(20000, 17)

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification,Unnamed: 16
0,54_GUTHRAM_2057,54,2057,Rebel Yell Root Beer Bourbon,50mL,8352,LUXCO INC,11719,8/19/2024,8/26/2024,9/4/2024,10/13/2024,1,120,92,1,NaN
1,76_DONCASTER_21609,76,21609,Josh Cellars Legacy Red,750mL,4425,MARTIGNETTI COMPANIES,11928,9/2/2024,9/6/2024,9/14/2024,10/24/2024,10,12,115,2,NaN
2,64_CESTERFIELD_5090,64,5090,El Charro Silver Tequila,750mL,8004,SAZERAC CO INC,12476,10/5/2024,10/13/2024,10/24/2024,12/3/2024,10,12,123,1,NaN
3,73_DONCASTER_3915,73,3915,Sauza Silver Tequila,750mL,12546,JIM BEAM BRANDS COMPANY,12222,9/22/2024,9/27/2024,10/4/2024,11/3/2024,9,24,228,1,NaN
4,57_LANTEGLOS_3041,57,3041,Zhenka Pink Lemonade Vodka,1.75L,9552,M S WALKER INC,12115,9/15/2024,9/23/2024,9/26/2024,11/6/2024,6,5,29,1,NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     20000 non-null  object
 1   Store           20000 non-null  int64
 2   Brand           20000 non-null  int64
 3   Description     20000 non-null  object
 4   Size            20000 non-null  object
 5   VendorNumber    20000 non-null  int64
 6   VendorName      20000 non-null  object
 7   PONumber        20000 non-null  int64
 8   PODate          20000 non-null  object
 9   ReceivingDate   20000 non-null  object
 10  InvoiceDate     20000 non-null  object
 11  PayDate         20000 non-null  object
 12  PurchasePrice   20000 non-null  int64
 13  Quantity        20000 non-null  int64
 14  Dollars         20000 non-null  int64
 15  Classification  20000 non-null  int64
 16  Unnamed: 16     0 non-null      float64
dtypes: float64(1), int64(8), object(8)
memory usage: 2.6+ MB

In [31]:
df.isnull().sum()

InventoryId           0
Store                 0
Brand                 0
Description           0
Size                  0
VendorNumber          0
VendorName            0
PONumber              0
PODate                0
ReceivingDate         0
InvoiceDate           0
PayDate               0
PurchasePrice         0
Quantity              0
Dollars               0
Classification        0
Unnamed: 16       20000
dtype: int64

In [32]:
df.duplicated().sum()

0

In [33]:
# Remove the completely empty column
df = df.drop(columns=["Unnamed: 16"])

# Convert date columns
date_columns = ["PODate", "ReceivingDate", "InvoiceDate", "PayDate"]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

# Check the dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     20000 non-null  object
 1   Store           20000 non-null  int64
 2   Brand           20000 non-null  int64
 3   Description     20000 non-null  object
 4   Size            20000 non-null  object
 5   VendorNumber    20000 non-null  int64
 6   VendorName      20000 non-null  object
 7   PONumber        20000 non-null  int64
 8   PODate          20000 non-null  datetime64[ns]
 9   ReceivingDate   20000 non-null  datetime64[ns]
 10  InvoiceDate     20000 non-null  datetime64[ns]
 11  PayDate         20000 non-null  datetime64[ns]
 12  PurchasePrice   20000 non-null  int64
 13  Quantity        20000 non-null  int64
 14  Dollars         20000 non-null  int64
 15  Classification  20000 non-null  int64
dtypes: datetime64[ns](4), int64(8), object(4)
memory usage: 2.4+ MB
None

In [34]:
df.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [35]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\purchases_sample_cleaned.csv",
    index=False
)

print("purchases_sample_cleaned.csv saved successfully")

purchases_sample_cleaned.csv saved successfully

**purchase_orders**

In [37]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\purchase_orders.csv")

print(df.shape)
df.head()

(29666, 9)

,po_id,supplier_id,site_id,part_id,order_date,promised_date,receipt_date,ordered_qty,received_qty
0,PO000001,SUP004,SITE01,P00001,5/2/2022,5/28/2022,5/29/2022,16,16
1,PO000002,SUP004,SITE01,P00001,7/4/2022,7/31/2022,8/2/2022,5,5
2,PO000003,SUP004,SITE01,P00001,10/17/2022,11/12/2022,11/16/2022,5,5
3,PO000004,SUP004,SITE01,P00001,2/6/2023,3/7/2023,3/9/2023,3,3
4,PO000005,SUP004,SITE01,P00001,4/3/2023,4/28/2023,4/29/2023,5,5

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29666 entries, 0 to 29665
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   po_id          29666 non-null  object
 1   supplier_id    29666 non-null  object
 2   site_id        29666 non-null  object
 3   part_id        29666 non-null  object
 4   order_date     29666 non-null  object
 5   promised_date  29666 non-null  object
 6   receipt_date   29666 non-null  object
 7   ordered_qty    29666 non-null  int64
 8   received_qty   29666 non-null  int64
dtypes: int64(2), object(7)
memory usage: 2.0+ MB

In [39]:
df.isnull().sum()

po_id            0
supplier_id      0
site_id          0
part_id          0
order_date       0
promised_date    0
receipt_date     0
ordered_qty      0
received_qty     0
dtype: int64

In [40]:
df.duplicated().sum()

0

In [41]:
import pandas as pd

# Convert date columns
date_columns = ['order_date', 'promised_date', 'receipt_date']

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29666 entries, 0 to 29665
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   po_id          29666 non-null  object
 1   supplier_id    29666 non-null  object
 2   site_id        29666 non-null  object
 3   part_id        29666 non-null  object
 4   order_date     29666 non-null  datetime64[ns]
 5   promised_date  29666 non-null  datetime64[ns]
 6   receipt_date   29666 non-null  datetime64[ns]
 7   ordered_qty    29666 non-null  int64
 8   received_qty   29666 non-null  int64
dtypes: datetime64[ns](3), int64(2), object(4)
memory usage: 2.0+ MB
None

In [42]:
df.isnull().sum()

po_id            0
supplier_id      0
site_id          0
part_id          0
order_date       0
promised_date    0
receipt_date     0
ordered_qty      0
received_qty     0
dtype: int64

In [43]:
df.to_csv(
    r'C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\purchase_orders_cleaned.csv',
    index=False
)

print('purchase_orders_cleaned.csv saved successfully')

purchase_orders_cleaned.csv saved successfully

**begin_inventory**

In [45]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\begin_inventory.csv")

print(df.shape)

df.head()

(206529, 9)

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,13,1/1/2024
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,11,1/1/2024
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,37,1/1/2024
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,39,1/1/2024
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,35,1/1/2024

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206529 entries, 0 to 206528
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  206529 non-null  object
 1   Store        206529 non-null  int64
 2   City         206529 non-null  object
 3   Brand        206529 non-null  int64
 4   Description  206529 non-null  object
 5   Size         206529 non-null  object
 6   onHand       206529 non-null  int64
 7   Price        206529 non-null  int64
 8   startDate    206529 non-null  object
dtypes: int64(4), object(5)
memory usage: 14.2+ MB

In [47]:
df.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
startDate      0
dtype: int64

In [48]:
df.duplicated().sum()

0

In [49]:
# Convert startDate to datetime
df["startDate"] = pd.to_datetime(df["startDate"], errors="coerce")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206529 entries, 0 to 206528
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  206529 non-null  object
 1   Store        206529 non-null  int64
 2   City         206529 non-null  object
 3   Brand        206529 non-null  int64
 4   Description  206529 non-null  object
 5   Size         206529 non-null  object
 6   onHand       206529 non-null  int64
 7   Price        206529 non-null  int64
 8   startDate    206529 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 14.2+ MB
None

In [50]:
df.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
startDate      0
dtype: int64

In [51]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\begin_inventory_cleaned.csv",
    index=False
)

print("begin_inventory_cleaned.csv saved successfully")

begin_inventory_cleaned.csv saved successfully

**end_inventory**

In [53]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\end_inventory.csv")

print(df.shape)

df.head()

(224489, 9)

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,13,12/31/2024
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,37,12/31/2024
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,39,12/31/2024
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,35,12/31/2024
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,15,12/31/2024

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224489 entries, 0 to 224488
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  224489 non-null  object
 1   Store        224489 non-null  int64
 2   City         223205 non-null  object
 3   Brand        224489 non-null  int64
 4   Description  224489 non-null  object
 5   Size         224489 non-null  object
 6   onHand       224489 non-null  int64
 7   Price        224489 non-null  int64
 8   endDate      224489 non-null  object
dtypes: int64(4), object(5)
memory usage: 15.4+ MB

In [55]:
df.isnull().sum()

InventoryId       0
Store             0
City           1284
Brand             0
Description       0
Size              0
onHand            0
Price             0
endDate           0
dtype: int64

In [56]:
df.duplicated().sum()

0

In [57]:
# Fill missing City values
df["City"] = df["City"].fillna("Unknown")

# Convert endDate to datetime
df["endDate"] = pd.to_datetime(df["endDate"], errors="coerce")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224489 entries, 0 to 224488
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  224489 non-null  object
 1   Store        224489 non-null  int64
 2   City         224489 non-null  object
 3   Brand        224489 non-null  int64
 4   Description  224489 non-null  object
 5   Size         224489 non-null  object
 6   onHand       224489 non-null  int64
 7   Price        224489 non-null  int64
 8   endDate      224489 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 15.4+ MB
None

In [58]:
df.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
endDate        0
dtype: int64

In [61]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\end_inventory_cleaned.csv",
    index=False
)

print("end_inventory_cleaned.csv saved successfully")

end_inventory_cleaned.csv saved successfully

**sales_sample**

In [62]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\sales_sample.csv")

print(df.shape)

df.head()

(20000, 17)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,14_BROMWICH_8200,14,8200,Chambord Liqueur de France,50mL,1,3,3,1/16/2024,50,1,0,1128,BROWN-FORMAN CORP,NaN,NaN,NaN
1,69_MOUNTMEND_21019,69,21019,Black Box Pnt Nr,3L,1,19,19,4/7/2024,3000,2,0,1392,CONSTELLATION BRANDS INC,NaN,NaN,NaN
2,69_MOUNTMEND_7143,69,7143,Smirnoff Watermelon Vodka,1.75L,1,20,20,7/28/2024,1750,1,2,3960,DIAGEO NORTH AMERICA INC,NaN,NaN,NaN
3,19_WINTERVALE_6590,19,6590,Almaden B/B Wh Znfdl Cal,5L,2,30,15,7/1/2024,5000,2,2,9815,WINE GROUP INC,NaN,NaN,NaN
4,53_HILLFAR_34133,53,34133,Turning Leaf RSV Cab Svgn,1.5L,1,10,10,5/14/2024,1500,2,0,3252,E & J GALLO WINERY,NaN,NaN,NaN

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     20000 non-null  object
 1   Store           20000 non-null  int64
 2   Brand           20000 non-null  int64
 3   Description     20000 non-null  object
 4   Size            20000 non-null  object
 5   SalesQuantity   20000 non-null  int64
 6   SalesDollars    20000 non-null  int64
 7   SalesPrice      20000 non-null  int64
 8   SalesDate       20000 non-null  object
 9   Volume          20000 non-null  int64
 10  Classification  20000 non-null  int64
 11  ExciseTax       20000 non-null  int64
 12  VendorNo        20000 non-null  int64
 13  VendorName      20000 non-null  object
 14  Unnamed: 14     0 non-null      float64
 15  Unnamed: 15     0 non-null      float64
 16  Unnamed: 16     0 non-null      float64
dtypes: float64(3), int64(9), object(5)
memory usage: 2.6+ MB

In [64]:
df.isnull().sum()

InventoryId           0
Store                 0
Brand                 0
Description           0
Size                  0
SalesQuantity         0
SalesDollars          0
SalesPrice            0
SalesDate             0
Volume                0
Classification        0
ExciseTax             0
VendorNo              0
VendorName            0
Unnamed: 14       20000
Unnamed: 15       20000
Unnamed: 16       20000
dtype: int64

In [65]:
df.duplicated().sum()

0

In [66]:
# Remove empty columns
df = df.drop(columns=["Unnamed: 14", "Unnamed: 15", "Unnamed: 16"])

# Convert SalesDate to datetime
df["SalesDate"] = pd.to_datetime(df["SalesDate"], errors="coerce")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     20000 non-null  object
 1   Store           20000 non-null  int64
 2   Brand           20000 non-null  int64
 3   Description     20000 non-null  object
 4   Size            20000 non-null  object
 5   SalesQuantity   20000 non-null  int64
 6   SalesDollars    20000 non-null  int64
 7   SalesPrice      20000 non-null  int64
 8   SalesDate       20000 non-null  datetime64[ns]
 9   Volume          20000 non-null  int64
 10  Classification  20000 non-null  int64
 11  ExciseTax       20000 non-null  int64
 12  VendorNo        20000 non-null  int64
 13  VendorName      20000 non-null  object
dtypes: datetime64[ns](1), int64(9), object(4)
memory usage: 2.1+ MB
None

In [67]:
df.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
SalesQuantity     0
SalesDollars      0
SalesPrice        0
SalesDate         0
Volume            0
Classification    0
ExciseTax         0
VendorNo          0
VendorName        0
dtype: int64

In [68]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\sales_sample_cleaned.csv",
    index=False
)

print("sales_sample_cleaned.csv saved successfully")

sales_sample_cleaned.csv saved successfully

**Procurement KPI Analysis Dataset**

In [69]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\Procurement KPI Analysis Dataset.csv")

print(df.shape)
df.head()

(777, 11)

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
0,PO-00001,Alpha_Inc,10/17/2023,10/25/2023,Office Supplies,Cancelled,1176,20.13,17.81,0,Yes
1,PO-00002,Delta_Logistics,4/25/2022,5/5/2022,Office Supplies,Delivered,1509,39.32,37.34,235,Yes
2,PO-00003,Gamma_Co,1/26/2022,2/15/2022,MRO,Delivered,910,95.51,92.26,41,Yes
3,PO-00004,Beta_Supplies,10/9/2022,10/28/2022,Packaging,Delivered,1344,99.85,95.52,112,Yes
4,PO-00005,Delta_Logistics,9/8/2022,9/20/2022,Raw Materials,Delivered,1180,64.07,60.53,171,No

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PO_ID             777 non-null    object
 1   Supplier          777 non-null    object
 2   Order_Date        777 non-null    object
 3   Delivery_Date     690 non-null    object
 4   Item_Category     777 non-null    object
 5   Order_Status      777 non-null    object
 6   Quantity          777 non-null    int64
 7   Unit_Price        777 non-null    float64
 8   Negotiated_Price  777 non-null    float64
 9   Defective_Units   777 non-null    int64
 10  Compliance        777 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 66.9+ KB

In [71]:
df.isnull().sum()

PO_ID                0
Supplier             0
Order_Date           0
Delivery_Date       87
Item_Category        0
Order_Status         0
Quantity             0
Unit_Price           0
Negotiated_Price     0
Defective_Units      0
Compliance           0
dtype: int64

In [72]:
df.duplicated().sum()

0

In [73]:
# Fill missing delivery dates
df["Delivery_Date"] = df["Delivery_Date"].fillna("Not Delivered")

# Convert Order_Date to datetime
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

# Convert only valid Delivery_Date values
mask = df["Delivery_Date"] != "Not Delivered"
df.loc[mask, "Delivery_Date"] = pd.to_datetime(
    df.loc[mask, "Delivery_Date"],
    errors="coerce"
)

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PO_ID             777 non-null    object
 1   Supplier          777 non-null    object
 2   Order_Date        777 non-null    datetime64[ns]
 3   Delivery_Date     777 non-null    object
 4   Item_Category     777 non-null    object
 5   Order_Status      777 non-null    object
 6   Quantity          777 non-null    int64
 7   Unit_Price        777 non-null    float64
 8   Negotiated_Price  777 non-null    float64
 9   Defective_Units   777 non-null    int64
 10  Compliance        777 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 66.9+ KB
None

In [74]:
df.isnull().sum()

PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     0
Compliance          0
dtype: int64

In [76]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\Procurement_KPI_Analysis_Dataset_cleaned.csv",
    index=False
)

print("Procurement_KPI_Analysis_Dataset_cleaned.csv saved successfully")

Procurement_KPI_Analysis_Dataset_cleaned.csv saved successfully

**Supply_Chain_Operations_Dataset**

In [85]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\raw\Supply_Chain_Operations_Dataset.csv")

print(df.shape)

df.head()

(30, 7)

,Product,Supplier,Warehouse Location,Quantity,Unit Price,Total Cost,Delivery Date
0,Widget A,Alpha Corp,Warehouse 3,45,16,721,6/5/2025
1,Widget A,Epsilon Co,Warehouse 1,85,24,2039,6/1/2025
2,Widget A,Beta Ltd,Warehouse 1,74,32,2375,6/18/2025
3,Widget B,Epsilon Co,Warehouse 2,38,25,958,6/9/2025
4,Widget A,Beta Ltd,Warehouse 3,64,20,1300,6/5/2025

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product             30 non-null     object
 1   Supplier            30 non-null     object
 2   Warehouse Location  30 non-null     object
 3   Quantity            30 non-null     int64
 4   Unit Price          30 non-null     int64
 5   Total Cost          30 non-null     int64
 6   Delivery Date       30 non-null     object
dtypes: int64(3), object(4)
memory usage: 1.8+ KB

In [80]:
df.isnull().sum()

Product               0
Supplier              0
Warehouse Location    0
Quantity              0
Unit Price            0
Total Cost            0
Delivery Date         0
dtype: int64

In [81]:
df.duplicated().sum()

0

In [82]:
# Convert Delivery Date to datetime
df["Delivery Date"] = pd.to_datetime(df["Delivery Date"], errors="coerce")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product             30 non-null     object
 1   Supplier            30 non-null     object
 2   Warehouse Location  30 non-null     object
 3   Quantity            30 non-null     int64
 4   Unit Price          30 non-null     int64
 5   Total Cost          30 non-null     int64
 6   Delivery Date       30 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 1.8+ KB
None

In [83]:
df.isnull().sum()

Product               0
Supplier              0
Warehouse Location    0
Quantity              0
Unit Price            0
Total Cost            0
Delivery Date         0
dtype: int64

In [86]:
df.to_csv(
    r"C:\Users\Admin\Documents\Enterprise Procurement & Vendor Performance Analytics\data\day 11 python cleaning\Supply_Chain_Operations_Dataset_cleaned.csv",
    index=False
)

print("Supply_Chain_Operations_Dataset_cleaned.csv saved successfully")

Supply_Chain_Operations_Dataset_cleaned.csv saved successfully

In [89]:
print("="*60)
print("DAY 11 VALIDATION")
print("="*60)

print("Total Rows :", df.shape[0])
print("\nNull Values:")
print(df.isnull().sum())

print("\nValidation Completed Successfully")

============================================================
DAY 11 VALIDATION
============================================================
Total Rows : 12256

Null Values:
Brand             0
Description       0
Price             0
Size              0
Volume            0
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

Validation Completed Successfully

In [90]:
assert df.shape[0] > 0, "Dataset contains no rows"
assert df.isnull().sum().sum() == 0, "Null values still exist"

print("All Assertions Passed Successfully")

All Assertions Passed Successfully